/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "bcryjmrdosfkeeopfxas" || ""
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJjcnlqbXJkb3Nma2Vlb3BmeGFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5ODU3OTIsImV4cCI6MjA3MDU2MTc5Mn0.ZWwg_oIK3Rr_43sJNGj7PEqOa6784sIqTKgkw-XZ14c" || ""

// Fallback configuration check
export const isConfigured = Boolean(projectId && publicAnonKey);